<template>
  <px-icon
    icon="face-thinking"
    flip="horizontal"
    color="orange"
    size="35"
    class="mr-10"
  />
  <px-icon
    icon="face-thinking"
    flip="vertical"
    color="orange"
    size="35"
    class="mr-10"
  />
  <px-icon
    icon="face-thinking"
    flip="both"
    color="orange"
    size="35"
    class="mr-10"
  />
  <px-icon
    icon="face-thinking"
    rotation="270"
    color="orange"
    size="35"
    class="mr-10"
  />
</template>
